### ISSUE TITLE
Epub building error

### ISSUE THREAD

**Issue by maning** [lmullen/jekyll-ebook#1]
I got this error when trying to create an epub:

jekyll-ebook epub.yml
/Library/Ruby/Site/1.8/rubygems/core_ext/kernel_require.rb:51:in `gem_original_require': /Library/Ruby/Gems/1.8/gems/jekyll-ebook-0.0.2/bin/../lib/jekyll-ebook/ebook.rb:63: syntax error, unexpected ')' (SyntaxError)
....manifest['epub-stylesheet'],).convert
                              ^
    from /Library/Ruby/Site/1.8/rubygems/core_ext/kernel_require.rb:51:in`require'
    from /Library/Ruby/Gems/1.8/gems/jekyll-ebook-0.0.2/bin/../lib/jekyll-ebook.rb:16
    from /Library/Ruby/Site/1.8/rubygems/core_ext/kernel_require.rb:51:in `gem_original_require'
    from /Library/Ruby/Site/1.8/rubygems/core_ext/kernel_require.rb:51:in`require'
    from /Library/Ruby/Gems/1.8/gems/jekyll-ebook-0.0.2/bin/jekyll-ebook:6
    from /usr/bin/jekyll-ebook:23:in `load'
    from /usr/bin/jekyll-ebook:23

**Comment by lmullen** [comment]
Thanks for the bug report. Can you please let me know two things? 

First, what version of Ruby and RubyGems are you running? You can find this by running the commands `ruby --version` and `gem --version` in your terminal.

Second, what command did you use that produced this error?

**Comment by maning** [comment]
@lmullen,

Here:

```
! ruby --version
ruby 1.8.7 (2012-02-08 patchlevel 358) [universal-darwin11.0]
! gem --version
2.0.5
```

Then I ran the following:

```
! jekyll-ebook epub.yml
/Library/Ruby/Site/1.8/rubygems/core_ext/kernel_require.rb:51:in `gem_original_require': /Library/Ruby/Gems
/1.8/gems/jekyll-ebook-0.0.2/bin/../lib/jekyll-ebook/ebook.rb:63: syntax error, unexpected ')' (SyntaxError)
....manifest['epub-stylesheet'],).convert
                              ^
    from /Library/Ruby/Site/1.8/rubygems/core_ext/kernel_require.rb:51:in `require'
    from /Library/Ruby/Gems/1.8/gems/jekyll-ebook-0.0.2/bin/../lib/jekyll-ebook.rb:16
    from /Library/Ruby/Site/1.8/rubygems/core_ext/kernel_require.rb:51:in `gem_original_require'
    from /Library/Ruby/Site/1.8/rubygems/core_ext/kernel_require.rb:51:in `require'
    from /Library/Ruby/Gems/1.8/gems/jekyll-ebook-0.0.2/bin/jekyll-ebook:6
    from /usr/bin/jekyll-ebook:23:in `load'
    from /usr/bin/jekyll-ebook:23
```

**Comment by lmullen** [comment]
The version of Ruby that you're using, which comes with OS X, is out-of-date. The Ruby developers have [stopped supporting](http://www.ruby-lang.org/en/news/2013/06/30/we-retire-1-8-7/) 1.8.7, and I can't take the time to support it either. 

You're best bet is to upgrade to Ruby 1.9.x or even better to 2.0.x. I've tested jekyll-ebook with both versions, and it works fine. You can install an up-to-date Ruby [here](http://www.ruby-lang.org/en/), or you can use rbenv (my favorite), rvm, or Homebrew to install new versions. 

Let me know if you have any trouble once you upgrade.

**Comment by maning** [comment]
I installed ruby 2.0.0 using rvm and then updated all gems (jekyll, pandoc, rdiscount, etc.).

```
! ruby -v
ruby 2.0.0p247 (2013-06-27 revision 41674) [x86_64-darwin11.4.2]

! gem --version
 2.0.5

! jekyll-ebook epub.yml
/Users/maning/.rvm/gems/ruby-2.0.0-p247/gems/jekyll-ebook-0.0.2/lib/jekyll-ebook/ebook.rb:32:in `+': no implicit conversion of Fixnum into String (TypeError)
    from /Users/maning/.rvm/gems/ruby-2.0.0-p247/gems/jekyll-ebook-0.0.2/lib/jekyll-ebook/ebook.rb:32:in `generate_content'
    from /Users/maning/.rvm/gems/ruby-2.0.0-p247/gems/jekyll-ebook-0.0.2/lib/jekyll-ebook/ebook.rb:58:in `generate_epub'
    from /Users/maning/.rvm/gems/ruby-2.0.0-p247/gems/jekyll-ebook-0.0.2/bin/jekyll-ebook:9:in `block in <top (required)>'
    from /Users/maning/.rvm/gems/ruby-2.0.0-p247/gems/jekyll-ebook-0.0.2/bin/jekyll-ebook:9:in `each'
    from /Users/maning/.rvm/gems/ruby-2.0.0-p247/gems/jekyll-ebook-0.0.2/bin/jekyll-ebook:9:in `<top (required)>'
    from /Users/maning/.rvm/gems/ruby-2.0.0-p247/bin/jekyll-ebook:23:in `load'
    from /Users/maning/.rvm/gems/ruby-2.0.0-p247/bin/jekyll-ebook:23:in `<main>'
    from /Users/maning/.rvm/gems/ruby-2.0.0-p247/bin/ruby_noexec_wrapper:14:in `eval'
    from /Users/maning/.rvm/gems/ruby-2.0.0-p247/bin/ruby_noexec_wrapper:14:in `<main>'
```

**Comment by lmullen** [comment]
Can you please post your file `epub.yml`? I think you have a problem with
your date.

## 

Lincoln Mullen

PhD candidate, Dept. of History, Brandeis University
lincoln@lincolnmullen.com | http://lincolnmullen.com

**Comment by maning** [comment]
I've solved the the data problem. But I still get a (new) error:

```
    jekyll-ebook epub.yml out.epub
    /Users/maning/.rvm/gems/ruby-2.0.0-p247/gems/pandoc-ruby-0.6.1/lib/pandoc-ruby.rb:102:in `write': Broken pipe (Errno::EPIPE)
        from /Users/maning/.rvm/gems/ruby-2.0.0-p247/gems/pandoc-ruby-0.6.1/lib/pandoc-ruby.rb:102:in `puts'
        from /Users/maning/.rvm/gems/ruby-2.0.0-p247/gems/pandoc-ruby-0.6.1/lib/pandoc-ruby.rb:102:in `block in execute'
        from /Users/maning/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/open3.rb:217:in `popen_run'
        from /Users/maning/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/open3.rb:99:in `popen3'
        from /Users/maning/.rvm/gems/ruby-2.0.0-p247/gems/pandoc-ruby-0.6.1/lib/pandoc-ruby.rb:101:in `execute'
        from /Users/maning/.rvm/gems/ruby-2.0.0-p247/gems/pandoc-ruby-0.6.1/lib/pandoc-ruby.rb:77:in `convert'
        from /Users/maning/.rvm/gems/ruby-2.0.0-p247/gems/jekyll-ebook-0.0.2/lib/jekyll-ebook/ebook.rb:63:in `generate_epub'
        from /Users/maning/.rvm/gems/ruby-2.0.0-p247/gems/jekyll-ebook-0.0.2/bin/jekyll-ebook:9:in `block in <top (required)>'
        from /Users/maning/.rvm/gems/ruby-2.0.0-p247/gems/jekyll-ebook-0.0.2/bin/jekyll-ebook:9:in `each'
        from /Users/maning/.rvm/gems/ruby-2.0.0-p247/gems/jekyll-ebook-0.0.2/bin/jekyll-ebook:9:in `<top (required)>'
        from /Users/maning/.rvm/gems/ruby-2.0.0-p247/bin/jekyll-ebook:23:in `load'
        from /Users/maning/.rvm/gems/ruby-2.0.0-p247/bin/jekyll-ebook:23:in `<main>'
        from /Users/maning/.rvm/gems/ruby-2.0.0-p247/bin/ruby_noexec_wrapper:14:in `eval'
        from /Users/maning/.rvm/gems/ruby-2.0.0-p247/bin/ruby_noexec_wrapper:14:in `<main>'
```

**Comment by lmullen** [comment]
1. Did you install the Pandoc executable and put it in your path?
2. Can you zip up all the files you're putting into the ebook and post a
   link to the ZIP? That will let me investigate the problem.

On Friday, July 19, 2013, Maning Sambale wrote:

> I've solved the the data problem. But I still get a (new) error:
> jekyll-ebook epub.yml out.epub
> /Users/maning/.rvm/gems/ruby-2.0.0-p247/gems/pandoc-ruby-0.6.1/lib/pandoc-ruby.rb:102:in
> write': Broken pipe (Errno::EPIPE)
> from
> /Users/maning/.rvm/gems/ruby-2.0.0-p247/gems/pandoc-ruby-0.6.1/lib/pandoc-ruby.rb:102:in
> puts'
> from
> /Users/maning/.rvm/gems/ruby-2.0.0-p247/gems/pandoc-ruby-0.6.1/lib/pandoc-ruby.rb:102:in
> block in execute'
> from
> /Users/maning/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/open3.rb:217:in
> popen_run'
> from
> /Users/maning/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/open3.rb:99:in
> popen3'
> from
> /Users/maning/.rvm/gems/ruby-2.0.0-p247/gems/pandoc-ruby-0.6.1/lib/pandoc-ruby.rb:101:in
> execute'
> from
> /Users/maning/.rvm/gems/ruby-2.0.0-p247/gems/pandoc-ruby-0.6.1/lib/pandoc-ruby.rb:77:in
> convert'
> from
> /Users/maning/.rvm/gems/ruby-2.0.0-p247/gems/jekyll-ebook-0.0.2/lib/jekyll-ebook/ebook.rb:63:in
> generate_epub'
> from
> /Users/maning/.rvm/gems/ruby-2.0.0-p247/gems/jekyll-ebook-0.0.2/bin/jekyll-ebook:9:in
> block in <top (required)>'
> from
> /Users/maning/.rvm/gems/ruby-2.0.0-p247/gems/jekyll-ebook-0.0.2/bin/jekyll-ebook:9:in
> each'
> from
> /Users/maning/.rvm/gems/ruby-2.0.0-p247/gems/jekyll-ebook-0.0.2/bin/jekyll-ebook:9:in
> <top (required)>'
> from /Users/maning/.rvm/gems/ruby-2.0.0-p247/bin/jekyll-ebook:23:inload'
> from /Users/maning/.rvm/gems/ruby-2.0.0-p247/bin/jekyll-ebook:23:in
> <main>'
> from /Users/maning/.rvm/gems/ruby-2.0.0-p247/bin/ruby_noexec_wrapper:14:in
> eval'
> from /Users/maning/.rvm/gems/ruby-2.0.0-p247/bin/ruby_noexec_wrapper:14:in
> `'
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/lmullen/jekyll-ebook/issues/1#issuecomment-21232776
> .

## 

## 

Lincoln Mullen

PhD candidate, Dept. of History, Brandeis University
lincoln@lincolnmullen.com | http://lincolnmullen.com
